<?php
/*
 * Copyright (c) 2013, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$form = new sly_Form($_router->getPlainUrl('imageresize', 'update'), 'POST', 'Image Resize ('.$version.')');

$maxCacheFiles = new sly_Form_Input_Number('max_cachefiles', t('iresize_max_cache_files'), $config['max_cachefiles']);
$maxCacheFiles->setBounds(0, 100, 1);
$form->add($maxCacheFiles);

$maxFilters = new sly_Form_Input_Number('max_filters', t('iresize_max_filters'), $config['max_filters']);
$maxFilters->setBounds(0, 100, 1);
$form->add($maxFilters);

$bytes = new sly_Form_Input_Number('max_resizekb', t('iresize_max_resizekb'), $config['max_resizekb']);
$bytes->setAnnotation('KB');
$form->add($bytes);

$pixel = new sly_Form_Input_Number('max_resizepixel', t('iresize_max_resizepx'), $config['max_resizepixel']);
$pixel->setAnnotation('Pixel');
$form->add($pixel);

$quality = new sly_Form_Input_Number('jpg_quality', t('iresize_jpg_quality'), $config['jpg_quality']);
$quality->setBounds(1, 100, 1);
$quality->setAnnotation('%');
$form->add($quality);

$upscaling = new sly_Form_Input_Checkbox('upscaling_allowed', t('iresize_upscaling'), 1, t('allowed'));
$upscaling->setChecked($config['upscaling_allowed']);
$form->add($upscaling);

$recompress = new sly_Form_Input_Checkbox('recompress', t('iresize_recompress'), 1, t('allowed'));
$recompress->setChecked($config['recompress']);
$form->add($recompress);

$appendHash = new sly_Form_Input_Checkbox('append_hash', t('iresize_append_hash'), 1, t('enabled'));
$appendHash->setChecked(!empty($config['append_hash']));
$form->add($appendHash);

$form->setResetButton(null);
$form->getSubmitButton()->setAttribute('value', t('update'));
print $form->render();
